# Build Linux workflow
name: build-linux-64

on:
  push:
    branches: [ master,beta ]
    paths-ignore:
      - "docs/**"
      - "dist/**"
      - "images/**"
      - "**.md"
      - "**.gitignore"
      - "**clog.py"
      - "**LICENSE"
      - "**-mac**"
      - "**-windows**"

    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Linux
        run: pyinstaller --clean --noconfirm specs/linux-64-terminservice.spec --add-data "tools/cloudscraper:./cloudscraper/"
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v7 
        with:
          add: 'dist/linux-64-terminservice --force'
          author_name: build_linux-64-workflow
          message: "Linux build workflow"
          remove: ''